#!/bin/bash 
STORE_MESSAGE="{\"type\":\"header\",\"relaycount\":\"1\",\"event\":\"1\",\"heat\":\"2\",\"gender\":null,\"round\":\"TIM\",\"swimstyle\":\"FREE\",\"distance\":\"100\",\"name\":null,\"competition\":\"WK 8 Bahnen\",\"lanes\":[{\"athleteid\":\"1244\",\"birthdate\":\"2003-01-01\",\"firstname\":\"Ann-Kathrin\",\"lastname\":\"Uzarek\",\"lane\":\"1\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"1\",\"finishtime\":\"0:52,49\",\"heat\":\"2\"},{\"athleteid\":\"1254\",\"birthdate\":\"2004-01-01\",\"firstname\":\"Siegfried\",\"lastname\":\"Welscher\",\"lane\":\"2\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"2\",\"finishtime\":\"0:58,21\",\"heat\":\"2\"},{\"athleteid\":\"1235\",\"birthdate\":\"2008-01-01\",\"firstname\":\"Rita \",\"lastname\":\"Fröse\",\"lane\":\"3\",\"entrytime\":\"NT\",\"name\":\"SV Unterwasser\",\"code\":\"00001\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"3\",\"finishtime\":\"0:25,52\",\"heat\":\"2\"},{\"athleteid\":\"1258\",\"birthdate\":\"2005-01-01\",\"firstname\":\"Lilly \",\"lastname\":\"Hirschochs\",\"lane\":\"4\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"4\",\"finishtime\":\"0:16,30\",\"heat\":\"2\"},{\"athleteid\":\"1239\",\"birthdate\":\"2005-01-01\",\"firstname\":\"Joshua \",\"lastname\":\"Wenig\",\"lane\":\"5\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"5\",\"finishtime\":\"1:57,18\",\"heat\":\"2\"},{\"athleteid\":\"1241\",\"birthdate\":\"2004-01-01\",\"firstname\":\"Steffen\",\"lastname\":\"Olbertz\",\"lane\":\"6\",\"entrytime\":\"NT\",\"name\":\"SV Unterwasser\",\"code\":\"00001\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"6\",\"finishtime\":\"0:37,84\",\"heat\":\"2\"},{\"athleteid\":\"1237\",\"birthdate\":\"2004-01-01\",\"firstname\":\"Wilma \",\"lastname\":\"Bachmann\",\"lane\":\"7\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"7\",\"finishtime\":\"0:50,14\",\"heat\":\"2\"},{\"type\":\"lane\",\"lane\":\"8\",\"event\":\"1\",\"place\":\"8\",\"finishtime\":\"1:28,41\",\"heat\":\"2\"}]}"

STORE_MESSAGE_2="{\"type\":\"header\",\"relaycount\":\"1\",\"event\":\"1\",\"heat\":\"3\",\"gender\":null,\"round\":\"TIM\",\"swimstyle\":\"FREE\",\"distance\":\"100\",\"name\":null,\"competition\":\"WK 8 Bahnen\",\"lanes\":[{\"athleteid\":\"1243\",\"birthdate\":\"2003-01-01\",\"firstname\":\"Torsten\",\"lastname\":\"Roling\",\"lane\":\"1\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"1\",\"finishtime\":\"0:44,34\",\"heat\":\"3\"},{\"athleteid\":\"1250\",\"birthdate\":\"2005-01-01\",\"firstname\":\"Evelyn\",\"lastname\":\"Gustenberg\",\"lane\":\"2\",\"entrytime\":\"NT\",\"name\":\"SV Unterwasser\",\"code\":\"00001\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"2\",\"finishtime\":\"1:1,38\",\"heat\":\"3\"},{\"athleteid\":\"1262\",\"birthdate\":\"1996-01-01\",\"firstname\":\"Günther\",\"lastname\":\"Hartz\",\"lane\":\"3\",\"entrytime\":\"NT\",\"name\":\"SV Unterwasser\",\"code\":\"00001\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"3\",\"finishtime\":\"0:12,85\",\"heat\":\"3\"},{\"athleteid\":\"1240\",\"birthdate\":\"2001-01-01\",\"firstname\":\"Irma\",\"lastname\":\"Herkenhoff\",\"lane\":\"4\",\"entrytime\":\"NT\",\"name\":\"SV Unterwasser\",\"code\":\"00001\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"4\",\"finishtime\":\"1:36,63\",\"heat\":\"3\"},{\"athleteid\":\"1256\",\"birthdate\":\"1999-01-01\",\"firstname\":\"Tom\",\"lastname\":\"Huppertz\",\"lane\":\"5\",\"entrytime\":\"NT\",\"name\":\"SV Unterwasser\",\"code\":\"00001\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"5\",\"finishtime\":\"1:13,95\",\"heat\":\"3\"},{\"athleteid\":\"1253\",\"birthdate\":\"2003-01-01\",\"firstname\":\"Marlon \",\"lastname\":\"Prigge\",\"lane\":\"6\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"6\",\"finishtime\":\"1:11,72\",\"heat\":\"3\"},{\"athleteid\":\"1259\",\"birthdate\":\"2000-01-01\",\"firstname\":\"Dieter\",\"lastname\":\"Zielinski\",\"lane\":\"7\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"7\",\"finishtime\":\"1:15,46\",\"heat\":\"3\"},{\"athleteid\":\"1252\",\"birthdate\":\"2004-01-01\",\"firstname\":\"Gina \",\"lastname\":\"Schimratzki\",\"lane\":\"8\",\"entrytime\":\"NT\",\"name\":\"SG Tieftaucher\",\"code\":\"00003\",\"type\":\"lane\",\"event\":\"1\",\"place\":\"8\",\"finishtime\":\"0:19,71\",\"heat\":\"3\"}]}"

MQTT_HOST=ubuntu
#MQTT_HOST=192.168.178.152
RAW_TOPIC=storechannel

send_main_message(){
    echo main: "$1"
    NEW_MESSAGE=$1
    #NEW_MESSAGE="{\"type\":\"$1\",\"size\":\"large\",\"finishtime\":\"1569662431\"}"
    mosquitto_pub -h $MQTT_HOST -t $RAW_TOPIC -m "$NEW_MESSAGE"
}

send_main_message "$STORE_MESSAGE"
send_main_message "$STORE_MESSAGE_2"